[2021-08-25 05:58:12,595] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-08-25 05:58:12,598] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-08-25 05:58:12,603] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-08-25 05:58:12,607] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-08-25 05:58:12,611] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-08-25 05:58:12,613] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-08-25 05:58:12,616] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-08-25 05:58:12,619] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-08-25 05:58:12,622] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-08-25 05:58:25,236] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-08-25 05:58:25,255] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-08-25 05:58:27,880] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-08-25 05:58:27,887] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-08-25 05:58:28,290] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-08-25 05:58:52,875] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:101 - Fail to decode or parse message, message discarded
[2021-08-25 05:58:52,881] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:102 - b'{"source": "file:/workspace/data/car.jpg", "context": {"project_id": "project_id","timecode": "timecode","debug": true, "interest_region": [[x1, y1], [x2, y2], [x3, y3], [x4, y4]], "object_filter": ["person", "bicycle", "car"]}, "data": {}, "action": "process", "prev": [], "next": []}'
[2021-08-25 05:58:52,885] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:103 - Expecting value: line 1 column 142 (char 141)
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 99, in _handler_fn
    job_msg = json.loads(message.body.decode())
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 142 (char 141)
[2021-08-25 06:02:15,803] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:101 - Fail to decode or parse message, message discarded
[2021-08-25 06:02:15,809] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:102 - b'{"source": "file:/workspace/data/car.jpg", "context": {"project_id": "project_id","timecode": "timecode","debug": true, "interest_region": [[x1, y1], [x2, y2], [x3, y3], [x4, y4]], "object_filter": ["person", "bicycle", "car"]}, "data": {}, "action": "process", "prev": [], "next": []}'
[2021-08-25 06:02:15,813] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:103 - Expecting value: line 1 column 142 (char 141)
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 99, in _handler_fn
    job_msg = json.loads(message.body.decode())
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 142 (char 141)
[2021-08-25 06:07:30,288] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:101 - Fail to decode or parse message, message discarded
[2021-08-25 06:07:30,296] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:102 - b'{"source": "file:/workspace/images/car.jpg", "context": {"project_id": "project_id","timecode": "timecode","debug": true, "interest_region": [[x1, y1], [x2, y2], [x3, y3], [x4, y4]], "object_filter": ["person", "bicycle", "car"]}, "data": {}, "action": "process", "prev": [], "next": []}'
[2021-08-25 06:07:30,301] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:103 - Expecting value: line 1 column 144 (char 143)
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 99, in _handler_fn
    job_msg = json.loads(message.body.decode())
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 144 (char 143)
[2021-08-25 06:14:26,946] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:163 - [Errno 2] No such file or directory: '/workspace/data/car.jpg'
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 160, in retrieve_source_fn
    async with async_open(file_key, 'rb') as afp:
  File "/usr/local/lib/python3.8/site-packages/aiofile/utils.py", line 179, in __aenter__
    await self.file.open()
  File "/usr/local/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/data/car.jpg'
[2021-08-25 06:14:27,172] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:282 - Message processing failed, message NOT requeued
[2021-08-25 06:14:27,178] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:283 - cannot identify image file <_io.BytesIO object at 0x7f49cb575c20>
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 178, in _handler_fn
    delegate_output_data = await self.handler.inference_handler(retrieve_source_fn, job_context, job_data, job_action)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 110, in inference_handler
    pil_img = pil_conversion(source_data)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 82, in pil_conversion
    image = Image.open(stream).convert('RGB')
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2958, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f49cb575c20>
[2021-08-25 06:15:19,102] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:141 - AttributeError("'list' object has no attribute 'split'")
[2021-08-25 06:15:19,108] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:370 - No downstream defined! Not sending message after message handler returns
[2021-08-25 06:19:04,017] [WARNING] __main__ main.py:182 - closing all external connections
[2021-08-25 06:19:04,025] [WARNING] __main__ main.py:192 - asyncmain cancelled
[2021-08-25 06:19:04,032] [WARNING] __main__ main.py:194 - asyncmain exiting
